// Generate core/builtinVocab.js (T-2.1) from the toeic-drill word data.
//
// Usage (from the repository root):
//   node Tools/Builtin/make_builtin.mjs <path to toeic-drill word-data folder>
//
// Reads every VOCAB_YYYY-MM-DD.js in that folder with Tools/Migrate/legacyFiles.mjs (shared with the T-8 migration:
// the aggregate _all.js is skipped and the window.__addVocab( ... ) wrapper removed), and parses each file with core/importFormat.js
// (legacy toeic-drill format), so pos aliases and the phrase kind are normalized the same way as imports.
// Words are deduplicated by keyOf (INV-4, first occurrence wins) and keep only the fields in
// Docs/21_Quiz.md section 4. The output is a generated file: fix this script, not the output.
// Report: Temp/tango-drill_builtin.txt (UV-4). Exit code 1 on any problem.
// Keep this file ASCII-only (UE-1).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseImport, LEGACY_FORMAT } from '../../core/importFormat.js';
import { keyOf } from '../../core/word.js';
import { readLegacyDays } from '../Migrate/legacyFiles.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const outPath = join(root, 'core', 'builtinVocab.js');
const reportPath = join(root, 'Temp', 'tango-drill_builtin.txt');
const FIELDS = ['en', 'pos', 'ja', 'kind'];

const src = process.argv[2];
const lines = [];
let fail = 0;

function finish() {
  mkdirSync(dirname(reportPath), { recursive: true });
  const head = ['tango-drill builtin vocabulary', `generated: ${new Date().toISOString()}`,
    `result: ${fail ? 'FAIL' : 'PASS'} (fail=${fail})`, ''];
  writeFileSync(reportPath, [...head, ...lines, ''].join('\n'), 'utf8');
  process.exit(fail ? 1 : 0);
}

if (!src) {
  fail++; lines.push('[FAIL] usage: node Tools/Builtin/make_builtin.mjs <word-data folder>');
  finish();
}

const days = readLegacyDays(src);
const files = days.map((d) => d.name);
if (!files.length) { fail++; lines.push(`[FAIL] no VOCAB_*.js in ${src}`); finish(); }

/** @type {Map<string, Record<string, string>>} */
const byKey = new Map();
let items = 0;
for (const { name: f, text } of days) {
  const r = parseImport(text);
  if (r.fatal || r.format !== LEGACY_FORMAT) {
    fail++; lines.push(`[FAIL] ${f}: ${r.fatal || 'format ' + r.format}`);
    continue;
  }
  for (const row of r.rows) {
    if (!row.word) { fail++; lines.push(`[FAIL] ${f} #${row.ref}: ${row.error || row.skipped}`); continue; }
    items++;
    const w = row.word;
    if (!w.ja) { fail++; lines.push(`[FAIL] ${f} #${row.ref}: no ja (${w.en})`); continue; }
    const k = keyOf(w);
    if (byKey.has(k)) continue;
    /** @type {Record<string, string>} */
    const o = {};
    for (const field of FIELDS) {
      const v = /** @type {Record<string, unknown>} */ (w)[field];
      if (typeof v === 'string' && v) o[field] = v;
    }
    byKey.set(k, o);
  }
}

const words = [...byKey.values()];
lines.push(`[${fail ? 'FAIL' : 'PASS'}] files=${files.length} items=${items} unique=${words.length}`);
lines.push('files read:', ...files.map((f) => '  ' + f));

if (!fail) {
  const body = words.map((w) => '  ' + JSON.stringify(w) + ',').join('\n');
  const out = [
    '// Generated by Tools/Builtin/make_builtin.mjs from the toeic-drill word data. Do not edit by hand.',
    '// Distractor-only vocabulary: never used as questions (INV-5). Fields: Docs/21_Quiz.md section 4.',
    '',
    "/** @type {readonly import('./word.js').Word[]} */",
    'export const BUILTIN_VOCAB = Object.freeze([',
    body,
    '].map((w) => Object.freeze(w)));',
    '',
  ].join('\n');
  writeFileSync(outPath, out, 'utf8');
  lines.push(`wrote core/builtinVocab.js (${words.length} words)`);
}
finish();
