// Extract the review-mix and stats code of toeic-drill verbatim, as the reference for the
// comparison test of T-3 (tests/core/review.compare.test.js).
//
// Usage (from the repository root):
//   node Tools/Legacy/extract_review.mjs <path to toeic-drill's word-drill html>
//
// The line ranges are pinned to toeic-drill commit a839c6d. Each range's first line is checked
// against an ASCII prefix, so a different version of the file stops the script instead of
// silently extracting the wrong lines. Browser globals the excerpts touch (localStorage,
// document, window, Math.random, the date) are replaced by stand-ins from `env`.
// Output: tests/core/fixtures/legacy/toeicDrillReview.js (generated: fix this script, not the output).
// Report: Temp/tango-drill_legacy.txt (UV-4). Exit code 1 on any problem.
// Keep this file ASCII-only (UE-1).
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const outPath = join(root, 'tests', 'core', 'fixtures', 'legacy', 'toeicDrillReview.js');
const reportPath = join(root, 'Temp', 'tango-drill_legacy.txt');

/** [first line, last line, prefix of the first line] (1-based, inclusive) */
const RANGES = [
  [171, 173, 'var daysData=[], passageDays=[]'],
  [251, 252, 'function normPos(w)'],
  [327, 330, 'var WEAK={};'],
  [332, 363, '// ---- '],
  [389, 436, 'function sessionsAsc(){'],
  [447, 454, 'function buildItems(d){'],
  [473, 474, 'function allItemsRaw(){'],
  [539, 569, 'function quizGroupLabel(k){'],
  [708, 749, 'function answerPairs(key){'],
  [833, 854, 'function csvCell(v){'],
];
/** The sort inside renderStats, wrapped as a function of its own */
const SORT = [790, 800, '  rows.sort(function(a,b){'];
/** How the app builds daysData after loading the data files */
const LOAD = [946, 946, '  daysData=window.__VOCAB.slice()'];

const src = process.argv[2];
const report = [];
let fail = 0;

function finish() {
  mkdirSync(dirname(reportPath), { recursive: true });
  const head = ['tango-drill legacy extract', `generated: ${new Date().toISOString()}`,
    `result: ${fail ? 'FAIL' : 'PASS'} (fail=${fail})`, ''];
  writeFileSync(reportPath, [...head, ...report, ''].join('\n'), 'utf8');
  process.exit(fail ? 1 : 0);
}

if (!src) { fail++; report.push('[FAIL] usage: node Tools/Legacy/extract_review.mjs <html>'); finish(); }

const raw = readFileSync(src);
const sha = createHash('sha256').update(raw).digest('hex');
const lines = raw.toString('utf8').split('\n').map((l) => l.replace(/\r$/, ''));

/** @param {[number, number, string]} r */
function take([a, b, prefix]) {
  const first = lines[a - 1] || '';
  if (!first.startsWith(prefix)) {
    fail++; report.push(`[FAIL] line ${a} does not start with ${JSON.stringify(prefix)}`);
  }
  if (lines[b - 1] === undefined) { fail++; report.push(`[FAIL] line ${b} does not exist`); }
  return lines.slice(a - 1, b).join('\n');
}

const parts = RANGES.map((r) => `// ---- lines ${r[0]}-${r[1]}\n` + take(/** @type {any} */ (r)));
const sortBody = take(/** @type {any} */ (SORT));
const load = take(/** @type {any} */ (LOAD));
if (fail) finish();

const out = `// @ts-nocheck
// Generated by Tools/Legacy/extract_review.mjs. Do not edit by hand.
// Verbatim excerpts of toeic-drill (commit a839c6d), source sha256 ${sha}.
// Reference implementation for the comparison test of T-3. Not shipped with the app.

/**
 * @param {{ days: object[], storage: Record<string, string>, today: string, random: () => number, kind?: string }} env
 */
export function makeLegacy(env) {
  var localStorage = {
    getItem: function (k) { return Object.prototype.hasOwnProperty.call(env.storage, k) ? env.storage[k] : null; },
    setItem: function (k, v) { env.storage[k] = String(v); },
  };
  var document = { getElementById: function (id) { return { value: id === 'daySel' ? 'qmix' : (env.kind || 'all') }; } };
  var window = { __VOCAB: env.days };
  var Math = Object.create(globalThis.Math);
  Math.random = env.random;
  function todayDateStr() { return env.today; }
  function render() {}

${parts.join('\n\n')}

// ---- lines ${SORT[0]}-${SORT[1]} (inside renderStats)
function legacySortRows(rows, by) {
  statSort = by;
${sortBody}
  return rows;
}

// ---- line ${LOAD[0]}
${load}

  return {
    daysData: function () { return daysData; },
    buildQuiz: function () { buildQuiz(); return quizSet; },
    allStats: allStats,
    statsCsv: statsCsv,
    sortRows: legacySortRows,
    firstDateOf: firstDateOf,
    recordAnswer: recordAnswer,
    storage: env.storage,
  };
}
`;
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out, 'utf8');
report.push(`[PASS] wrote tests/core/fixtures/legacy/toeicDrillReview.js from ${RANGES.length + 2} ranges`);
report.push(`source sha256: ${sha}`);
finish();
