// @ts-nocheck
// Generated by Tools/Legacy/extract_review.mjs. Do not edit by hand.
// Verbatim excerpts of toeic-drill (commit a839c6d), source sha256 0fdc76b30d975259ae45ec795be86fbf946aabd98b0bcc88902f9eb3bc5e597a.
// Reference implementation for the comparison test of T-3. Not shipped with the app.

/**
 * @param {{ days: object[], storage: Record<string, string>, today: string, random: () => number, kind?: string }} env
 */
export function makeLegacy(env) {
  var localStorage = {
    getItem: function (k) { return Object.prototype.hasOwnProperty.call(env.storage, k) ? env.storage[k] : null; },
    setItem: function (k, v) { env.storage[k] = String(v); },
  };
  var document = { getElementById: function (id) { return { value: id === 'daySel' ? 'qmix' : (env.kind || 'all') }; } };
  var window = { __VOCAB: env.days };
  var Math = Object.create(globalThis.Math);
  Math.random = env.random;
  function todayDateStr() { return env.today; }
  function render() {}

// ---- lines 171-173
var daysData=[], passageDays=[], mode='list', cardIdx=0, cardBack=false, quizSet=[], quizIdx=0, quizOk=0;
// 【項目15】2段階クイズの状態。stage 1=自己申告, 2=選択肢。self は第1段階の答え（null/1/0）。
var quizStage=1, quizSelf=null, quizOpts=null, quizOptsIdx=-1;

// ---- lines 251-252
function normPos(w){ return String(w.pos||'').replace(/[（(][^）)]*[）)]/g,'').trim(); }
function keyOf(w){ return w.en+'|'+normPos(w); }

// ---- lines 327-330
var WEAK={};
try{WEAK=JSON.parse(localStorage.getItem('toeic_vocab_weak')||'{}');}catch(e){WEAK={};}
function saveWeak(){try{localStorage.setItem('toeic_vocab_weak',JSON.stringify(WEAK));}catch(e){}}
function toggleWeak(w,el){ if(WEAK[w]){delete WEAK[w];el.classList.remove('on');}else{WEAK[w]=1;el.classList.add('on');} saveWeak(); }

// ---- lines 332-363
// ---- 項目10: 復習ミックス（今日／n_1回前／n_2回前／よく間違える語）----
// 調整用の定数。n は「今日と合わせて最大3日次」の制約内（過去2日まで）。
// 【項目14】出題数の上限は撤廃。対象プールの全件を出す。
// 群ごとの重み付け(QUIZ_TARGET)は不要になったので、代わりに「出題順」を規定する。
var QUIZ_N1=1;         // n_1: 1回前（項目34で日付基準から回数基準へ）
var QUIZ_N2=3;         // n_2: 3回前
var QUIZ_M=5;          // 「よく間違える」判定に見る直近の出題回数
var QUIZ_P=2;          // 直近M回のうちこの回数以上間違えたら対象
// 【項目17】「回答数が少ない語」群の上限。
// 他の群（今日/n回前）は回で母集団が絞られ、miss も該当語だけなので自然に有限。
// この群だけは母集団が「全期間の全語」で、初期は全語が0回なので上限が無いと際限なく増える。
var QUIZ_FEW=10;
var QUIZ_ORDER=['today','d1','d3','miss','few'];  // 復習ミックスの出題順。群の中はシャッフルする

// 語ごとの直近正誤履歴（1=正解, 0=誤答）。直近10件まで保持。
var HIST={};
try{HIST=JSON.parse(localStorage.getItem('toeic_vocab_hist')||'{}');}catch(e){HIST={};}
function saveHist(){try{localStorage.setItem('toeic_vocab_hist',JSON.stringify(HIST));}catch(e){}}
function recordResult(en,ok){ var a=HIST[en]||[]; a.push(ok?1:0); if(a.length>10)a=a.slice(-10); HIST[en]=a; saveHist(); }
function missOften(en){ var a=(HIST[en]||[]).slice(-QUIZ_M); var wrong=0; a.forEach(function(x){if(x===0)wrong++;}); return wrong>=QUIZ_P; }

/** 【項目15】第1段階の自己申告（1=わかる, 0=わからない）。HIST と必ず同じ回数だけ積む。
    「わかると思ったが違った（思い違い）」を後から数えられるようにするための記録。
    HIST と足並みを揃えるため、記録は必ず recordResult と同時に行う。 */
var SELF={};
try{SELF=JSON.parse(localStorage.getItem('toeic_vocab_self')||'{}');}catch(e){SELF={};}
function saveSelf(){try{localStorage.setItem('toeic_vocab_self',JSON.stringify(SELF));}catch(e){}}
/** 正誤と自己申告を1回分まとめて記録する。片方だけ積むと対応が崩れるので、必ずこれを通す。 */
function recordAnswer(key,ok,self){
  recordResult(key,ok);
  var a=SELF[key]||[]; a.push(self?1:0); if(a.length>10)a=a.slice(-10); SELF[key]=a; saveSelf();
}

// ---- lines 389-436
function sessionsAsc(){
  return daysData.filter(function(d){ return (d.items||[]).length; });
}
/** 基準にする回の位置（今日以前で最も新しい回）。無ければ -1。 */
function sessionIdx(){
  var ss=sessionsAsc(), t=todayDateStr(), i=-1;
  ss.forEach(function(d,k){ if(d.date<=t) i=k; });
  return i;
}
/** n回前の回の項目。0 は基準の回そのもの。 */
function qAgo(n){
  var ss=sessionsAsc(), i=sessionIdx()-n;
  return (i>=0 && i<ss.length) ? (ss[i].items||[]).slice() : [];
}
function qToday(){ return qAgo(0); }
/** 群の見出し。基準の回が今日なら「今日」、そうでなければ「直近(M/D)」と出します。 */
function agoLabel(n){
  if(n>0) return n+'回前';
  var ss=sessionsAsc(), i=sessionIdx();
  if(i<0) return '直近';
  var d=ss[i].date;
  return d===todayDateStr() ? '今日' : ('直近('+d.slice(5).replace('-','/')+')');
}
function qMiss(){ return allItemsRaw().filter(function(w){return missOften(keyOf(w));}); }
/** 語の総回答回数（履歴の件数）。未回答は0。 */
function answerCount(en){ return (HIST[en]||[]).length; }
/** 【項目17】回答数が少ない語。未回答を最優先に、少ない順で QUIZ_FEW 件まで。
    同数のときはランダムに散らす（毎回同じ語が並ばないように）。

    exclude（既に他の群に入った語の集合）を先に除いてから選ぶ。
    今日の語は当日どれも0回なので、除外しないと上位を独占し、
    重複除去の結果この群が空になってしまう。 */
function qFew(exclude){
  exclude=exclude||{};
  return shuffleArr(allItemsRaw())
    .filter(function(w){ return !exclude[keyOf(w)]; })
    .sort(function(a,b){ return answerCount(keyOf(a))-answerCount(keyOf(b)); })
    .slice(0, QUIZ_FEW);
}
/** 今日/n回前/よく間違える に含まれる語の集合（few群の除外用） */
function qCoveredSet(){
  var m={};
  [qToday(), qAgo(QUIZ_N1), qAgo(QUIZ_N2), qMiss()].forEach(function(list){
    list.forEach(function(w){ m[keyOf(w)]=1; });
  });
  return m;
}
function shuffleArr(a){ a=a.slice(); for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=a[i];a[i]=a[j];a[j]=t;} return a; }

// ---- lines 447-454
function buildItems(d){
  var a=[];
  (d.words||[]).forEach(function(w){var o={};for(var k in w)o[k]=w[k];o.kind='word';a.push(o);});
  (d.phrases||[]).forEach(function(p){var o={};for(var k in p)o[k]=p[k];o.kind='phrase';o.pos=o.pos||'句';a.push(o);});
  d.items=a; return d;
}
function typeOf(){var e=document.getElementById('typeSel');return e?e.value:'all';}
function filterKind(a){var t=typeOf();return t==='all'?a:a.filter(function(x){return x.kind===t;});}

// ---- lines 473-474
function allItemsRaw(){var a=[];daysData.forEach(function(d){a=a.concat(d.items||[]);});return a;}
function allWords(){return filterKind(allItemsRaw());}

// ---- lines 539-569
function quizGroupLabel(k){
  if(k==='today')return agoLabel(0);
  if(k==='d1')return agoLabel(QUIZ_N1);
  if(k==='d3')return agoLabel(QUIZ_N2);
  if(k==='miss')return 'よく間違える';
  if(k==='few')return '回答数が少ない';
  return k;
}
function buildQuiz(){
  var v=document.getElementById('daySel').value;
  var chosen=[], seen={};
  if(v==='qmix'){
    // 【項目14】全件を出す。QUIZ_ORDER の順に群を並べ、群の中だけシャッフルする。
    // どの群から出ているかを quizGroup に持たせ、進捗表示に使う。
    var g={today:filterKind(qToday()), d1:filterKind(qAgo(QUIZ_N1)), d3:filterKind(qAgo(QUIZ_N2)),
           miss:filterKind(qMiss()), few:filterKind(qFew(qCoveredSet()))};
    QUIZ_ORDER.forEach(function(k){
      // few 群は qFew() が回答数の少ない順に並べているので、その順を保つ
      // （途中でやめても「最も測れていない語」から消化できる）。他の群は群内をシャッフル。
      var list = (k==='few') ? (g[k]||[]) : shuffleArr(g[k]||[]);
      list.forEach(function(w){
        var kk=keyOf(w);
        if(!seen[kk]){ seen[kk]=1; var o={};for(var p in w)o[p]=w[p]; o.quizGroup=k; chosen.push(o); }
      });
    });
  } else {
    chosen=shuffleArr(pool());
  }
  quizSet=chosen; quizIdx=0; quizOk=0; resetStage();
}
function resetStage(){ quizStage=1; quizSelf=null; quizOpts=null; quizOptsIdx=-1; }

// ---- lines 708-749
function answerPairs(key){
  var h=HIST[key]||[], sf=SELF[key]||[], off=h.length-sf.length, out=[];
  for(var i=0;i<h.length;i++){
    var j=i-off;
    out.push({ok:h[i]===1, self:(j>=0&&j<sf.length)?(sf[j]===1):null});
  }
  return out;
}

/** 語ごとの集計。
    思い違い = 「わかる」と申告して外した回数。missOften だけでは拾えない
    「覚えたつもり」の語を見つけるための指標（項目15の副産物）。 */
function statOf(w){
  var key=keyOf(w), ps=answerPairs(key);
  var correct=0, wrong=0, mis=0, said=0, unknown=0;
  ps.forEach(function(p){
    if(p.ok)correct++; else wrong++;
    if(p.self===true){ said++; if(!p.ok)mis++; }
    else if(p.self===false){ unknown++; }
  });
  return {w:w, key:key, pairs:ps, n:ps.length, correct:correct, wrong:wrong,
          mis:mis, said:said, unknown:unknown,
          acc:ps.length?correct/ps.length:null,
          misRate:said?mis/said:null,
          weak:!!WEAK[key], often:missOften(key)};
}
function allStats(){
  var seen={}, out=[];
  allItemsRaw().forEach(function(w){ var k=keyOf(w); if(!seen[k]){seen[k]=1;out.push(statOf(w));} });
  return out;
}
/** その語が最初に出た日。CSV と並び替えに使う。 */
var _firstDate={};
function firstDateOf(key){
  if(!Object.keys(_firstDate).length){
    daysData.forEach(function(d){ (d.items||[]).forEach(function(w){
      var k=keyOf(w); if(!_firstDate[k])_firstDate[k]=d.date; }); });
  }
  return _firstDate[key]||'';
}

var statSort='mis', statOnlyAnswered=true;

// ---- lines 833-854
function csvCell(v){
  var s=String(v==null?'':v);
  return /[",\n\r]/.test(s) ? '"'+s.replace(/"/g,'""')+'"' : s;
}
function statsCsv(){
  var cols=['en','pos','trans','ja','kind','key','firstDate',
            'answers','correct','wrong','accuracy','misbelief','saidKnown','misbeliefRate','unknown',
            'history','self','starred','oftenWrong'];
  var lines=[cols.join(',')];
  allStats().forEach(function(x){
    var w=x.w;
    lines.push([
      w.en, w.pos||'', w.trans||'', w.ja||'', w.kind||'', x.key, firstDateOf(x.key),
      x.n, x.correct, x.wrong, x.acc==null?'':Math.round(x.acc*1000)/1000,
      x.mis, x.said, x.misRate==null?'':Math.round(x.misRate*1000)/1000, x.unknown,
      x.pairs.map(function(p){return p.ok?1:0;}).join(' '),
      x.pairs.map(function(p){return p.self==null?'-':(p.self?1:0);}).join(' '),
      x.weak?1:0, x.often?1:0
    ].map(csvCell).join(','));
  });
  return lines.join('\r\n');
}

// ---- lines 790-800 (inside renderStats)
function legacySortRows(rows, by) {
  statSort = by;
  rows.sort(function(a,b){
    if(statSort==='mis'){
      var am=a.misRate==null?-1:a.misRate, bm=b.misRate==null?-1:b.misRate;
      if(bm!==am)return bm-am;
      return b.mis-a.mis;
    }
    if(statSort==='wrong'){ if(b.wrong!==a.wrong)return b.wrong-a.wrong; return (b.acc==null?0:1-b.acc)-(a.acc==null?0:1-a.acc); }
    if(statSort==='few'){ return a.n-b.n; }
    var ad=firstDateOf(a.key), bd=firstDateOf(b.key);
    return ad<bd?1:(ad>bd?-1:0);
  });
  return rows;
}

// ---- line 946
  daysData=window.__VOCAB.slice().sort(function(a,b){return a.date<b.date?-1:1;}).map(buildItems);

  return {
    daysData: function () { return daysData; },
    buildQuiz: function () { buildQuiz(); return quizSet; },
    allStats: allStats,
    statsCsv: statsCsv,
    sortRows: legacySortRows,
    firstDateOf: firstDateOf,
    recordAnswer: recordAnswer,
    storage: env.storage,
  };
}
